### ISSUE TITLE
Peer Review on PR 12

### ISSUE THREAD

**Issue by ahangarha** [Bavon101/my_portfolio#13]
Regarding PR https://github.com/Bavon101/my_portfolio/pull/12 the code is nicely organized and easy to read and understand.

As per task requirements:
- there should be a linter error for not having empty line at the end of the file

Beyond requirements of the task.
- It would be good to check if the browser supports and provide access to the localStorage 
- It would be good to empty form and relevant data in localStrorage on form successful submission.
- Maybe it is better to make a function for getting and setting values to form fields rather than defining form fields in global scope.

**Comment by Bavon101** [comment]
@ahangarha Thanks for catching this, I will work on the highlighted issues 🐱‍🏍.
